#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Standalone test script for WSVT absolute phase measurement.

This script calls the executor directly with hardcoded parameters pointing
to the test data. No GUI, no facade, no manager — just the core algorithm.

Test data location: C:\data\WSVT_abs_test\sample_in
  - 51 TIFF files: Mask5um_0001.tif through Mask5um_0051.tif
  - parameters.json: scan positions in mm

Mask pattern: Data/absolute_phase/mask/RanMask_2um_4mm.npy

Usage:
    python tests/test_wsvt_absolute_phase.py
"""

import os
import sys
import time
import numpy as np

# Add project root to path so imports work
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, project_root)

from aps.wf_suite.absolute_phase.legacy.process_images_WSVT_executor import execute_process_images_WSVT


def main():
    # ===================== Control flags =====================
    # Set True to skip pattern finding and use pre-computed simulated reference stack
    # (requires a previous run with use_saved_simulation=False to generate the files)
    use_saved_simulation = False

    # ===================== Test data paths =====================
    image_directory = r"C:\data\WSVT_abs_test\refs"
    scan_positions_file = os.path.join(image_directory, "parameters.json")
    pattern_path = os.path.join(project_root, "Data", "absolute_phase", "mask", "RanMask5umB0.npy")
    data_directory = os.path.join(project_root, "Data")
    result_folder = r"C:\data\WSVT_abs_test\results"

    # Pre-computed simulation paths (generated by a previous run)
    if use_saved_simulation:
        simulated_ref_stack_path = os.path.join(result_folder, "simulated_ref_stack.npz")
        assert os.path.isfile(simulated_ref_stack_path), \
            f"Saved simulation not found: {simulated_ref_stack_path}\nRun with use_saved_simulation=False first."
    else:
        simulated_ref_stack_path = None

    # Verify paths exist
    assert os.path.isdir(image_directory), f"Image directory not found: {image_directory}"
    assert os.path.isfile(scan_positions_file), f"Scan positions file not found: {scan_positions_file}"
    assert os.path.isfile(pattern_path), f"Pattern file not found: {pattern_path}"
    assert os.path.isdir(data_directory), f"Data directory not found: {data_directory}"

    print("=" * 70)
    print("WSVT Absolute Phase Test")
    print("=" * 70)
    print(f"use_saved_simulation: {use_saved_simulation}")
    print(f"Image directory:      {image_directory}")
    print(f"Scan positions file:  {scan_positions_file}")
    print(f"Pattern path:         {pattern_path}")
    print(f"Data directory:       {data_directory}")
    print(f"Result folder:        {result_folder}")
    print("=" * 70)

    t_start = time.time()

    # ===================== Run WSVT absolute phase =====================
    result = execute_process_images_WSVT(
        # Data paths
        image_directory=image_directory,
        scan_positions_file=scan_positions_file,
        data_directory=data_directory,
        result_folder=result_folder,
        pattern_path=pattern_path,
        simulated_ref_stack=simulated_ref_stack_path,  # None=compute from scratch, or path to skip pattern finding
        process_after_mask=True,       # continue to WSVT processing after generating the mask + ref stack
        saving_path=result_folder,     # save propagated patterns here

        # Scan parameters
        n_scan=51,                     # use all 51 scan positions
        sign_x=1,                      # fallback if auto_sign can't determine
        sign_y=1,                      # fallback if auto_sign can't determine
        auto_sign=True,                # auto-detect sign_x/sign_y from first two images
        position_units="mm",           # positions in parameters.json are in mm

        # Optics parameters — adjust these for your beamline setup
        p_x=0.65e-6,                   # detector pixel size [m]
        det_res=1.5e-6,                # detector spatial resolution [m]
        energy=20.0e3,                   # X-ray energy [eV]
        pattern_size=5e-6,             # mask pattern pixel size [m] — 2um for RanMask_2um
        pattern_thickness=1.5e-6,      # mask pattern thickness [m]
        pattern_T=0.8,               # mask pattern transmission
        d_prop=500e-3,                 # mask-to-detector distance [m]
        d_source_v=35.0,               # vertical source distance [m]
        d_source_h=35.0,               # horizontal source distance [m]
        source_v=1e-5,                # vertical source size [m]
        source_h=1e-5,               # horizontal source size [m]
        propagator='RS',               # propagation method

        # Pattern search parameters
        correct_scale=False,
        show_alignFigure=False,
        d_source_recal=True,          # set True to recalculate source distance from pattern search
        estimation_method='simple_speckle', # 'geometric' or 'simple_speckle'
        img_transfer_matrix=[1, 1, 0],
        find_transferMatrix=False,

        # Image processing
        #crop=[0, -1, 0, -1],           # full image (no crop)
        crop = [500],
        dark=None,                     # no dark image
        flat=None,                     # auto-generate flat
        rebinning=1,                   # no rebinning

        # WSVT solver parameters
        cal_half_window=20,            # half window for WSVT calculation
        n_cores=8,                     # CPU cores for parallel processing
        n_group=1,                     # memory groups
        use_wavelet=True,             # wavelet transform
        wavelet_lv_cut=0,             # wavelet level cut
        pyramid_level=0,               # pyramid level
        n_iter=1,                      # iterations
        use_GPU=False,                 # GPU acceleration
        scaling_x=1.0,                 # x pixel scaling
        scaling_y=1.0,                 # y pixel scaling

        # Output
        verbose=True,
        save_images=True,
    )

    t_end = time.time()

    print("\n" + "=" * 70)
    print("WSVT Absolute Phase Test COMPLETE")
    print(f"Total time: {t_end - t_start:.1f} seconds")
    print(f"Results saved to: {result_folder}")
    print("=" * 70)

    # Print result summary
    if result is not None:
        print(f"\nMode: {result['mode']}")
        print(f"Phase shape: {result['phase'].shape}")
        print(f"Intensity shape: {result['intensity'].shape}")
        print(f"Line displace Y shape: {result['line_displace'][0].shape}")
        print(f"Line displace X shape: {result['line_displace'][1].shape}")
        print(f"Line phase Y shape: {result['line_phase'][0].shape}")
        print(f"Line phase X shape: {result['line_phase'][1].shape}")
        print(f"Line curve Y shape: {result['line_curve'][0].shape}")
        print(f"Line curve X shape: {result['line_curve'][1].shape}")

        print(f"\nPhase range: [{result['phase'].min():.4f}, {result['phase'].max():.4f}] rad")
        print(f"Phase PV: {result['phase'].max() - result['phase'].min():.4f} rad")
        print(f"Phase RMS: {np.std(result['phase']):.4f} rad")


if __name__ == '__main__':
    main()
