#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Standalone test script for single-shot WXST absolute phase measurement.

This script calls execute_process_image() directly with hardcoded parameters
pointing to the first image from the WSVT test data. This validates that the
single-image absolute phase analysis works with the data before attempting
multi-image WSVT analysis.

Test data location: C:\data\WSVT_abs_test\sample_in
  - Uses the first TIF file (alphabetically sorted)

Mask pattern: Data/absolute_phase/mask/RanMask5umB0.npy

Usage:
    python tests/test_wxst_absolute_phase.py
"""

import os
import sys
import glob
import time

# Add project root to path so imports work
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, project_root)

from aps.wf_suite.absolute_phase.legacy.process_images_executor import execute_process_image


def main():
    # ===================== Control flags =====================
    # Set True to skip pattern finding and use pre-computed simulated reference
    # (requires a previous run with use_saved_simulation=False to generate the files)
    use_saved_simulation = True

    # ===================== Test data paths =====================
    image_directory = r"C:\data\WSVT_abs_test\refs"
    data_directory = os.path.join(project_root, "Data")
    pattern_path = os.path.join(project_root, "Data", "absolute_phase", "mask", "RanMask5umB0.npy")

    # Find the first TIF file (alphabetically sorted, same as load_images does)
    tif_files = sorted(glob.glob(os.path.join(image_directory, "*.tif")))
    assert len(tif_files) > 0, f"No TIF files found in: {image_directory}"
    first_image = tif_files[0]

    # Result and simulated mask directories
    result_folder = r"C:\data\WSVT_abs_test\wxst_results"
    simulated_mask_dir = os.path.join(result_folder, "simulated_mask")

    # Pre-computed simulation paths (generated by a previous run)
    if use_saved_simulation:
        propagated_pattern_path = os.path.join(simulated_mask_dir, "propagated_pattern.npz")
        propagated_patternDet_path = os.path.join(simulated_mask_dir, "propagated_patternDet.npz")
        assert os.path.isfile(propagated_pattern_path), \
            f"Saved simulation not found: {propagated_pattern_path}\nRun with use_saved_simulation=False first."
        assert os.path.isfile(propagated_patternDet_path), \
            f"Saved simulation not found: {propagated_patternDet_path}\nRun with use_saved_simulation=False first."
    else:
        propagated_pattern_path = None
        propagated_patternDet_path = None

    # Create output directories
    os.makedirs(result_folder, exist_ok=True)
    os.makedirs(simulated_mask_dir, exist_ok=True)

    # Verify paths exist
    assert os.path.isdir(image_directory), f"Image directory not found: {image_directory}"
    assert os.path.isfile(pattern_path), f"Pattern file not found: {pattern_path}"
    assert os.path.isdir(data_directory), f"Data directory not found: {data_directory}"

    print("=" * 70)
    print("WXST Single-Shot Absolute Phase Test")
    print("=" * 70)
    print(f"use_saved_simulation: {use_saved_simulation}")
    print(f"Image file:           {first_image}")
    print(f"Pattern path:         {pattern_path}")
    print(f"Data directory:       {data_directory}")
    print(f"Result folder:        {result_folder}")
    print(f"Simulated mask dir:   {simulated_mask_dir}")
    print("=" * 70)

    t_start = time.time()

    # ===================== Run single-shot absolute phase =====================
    result = execute_process_image(
        # Data paths
        img=first_image,
        image_data=None,
        result_folder=result_folder,
        data_directory=data_directory,
        pattern_path=pattern_path,
        propagated_pattern=propagated_pattern_path,        # None=compute from scratch, or path to skip
        propagated_patternDet=propagated_patternDet_path,  # None=compute from scratch, or path to skip
        process_after_mask=True,        # continue to WXST processing after generating the mask
        saving_path=simulated_mask_dir, # save propagated patterns here

        # Pattern search parameters
        crop=[500],                     # central crop of 500x500
        img_transfer_matrix=[1, 1, 0],       # auto-search
        find_transferMatrix=True,       # search for the transfer matrix

        # Optics parameters — same as WSVT test
        p_x=0.65e-6,                    # detector pixel size [m]
        det_res=1.5e-6,                 # detector spatial resolution [m]
        energy=20.0e3,                  # X-ray energy [eV]
        pattern_size=5e-6,              # mask pattern pixel size [m]
        pattern_thickness=1.5e-6,       # mask pattern thickness [m]
        pattern_T=0.613,                # mask pattern transmission
        d_prop=500e-3,                  # mask-to-detector distance [m]
        d_source_v=27.0,                # vertical source distance [m]
        d_source_h=35.0,               # horizontal source distance [m]
        source_v=1e-6,                  # vertical source size [m]
        source_h=1e-6,                  # horizontal source size [m]
        propagator='RS',                # propagation method

        # Reconstruction parameters
        correct_scale=False,
        show_alignFigure=False,
        d_source_recal=True,
        cali_path=None,
        mode='area',                    # 'area' for full 2D analysis
        lineWidth=10,
        rebinning=1,
        down_sampling=1,
        crop_boundary=-1,

        # Speckle tracking parameters
        method='WXST',
        GPU=False,
        use_wavelet=True,
        wavelet_lv_cut=0,
        pyramid_level=0,
        n_iter=1,
        template_size=21,
        window_searching=20,
        nCores=8,
        nGroup=1,

        # Dark/flat
        dark=None,
        flat=None,

        # Output
        verbose=True,
        save_images=True,
    )

    t_end = time.time()

    print("\n" + "=" * 70)
    print("WXST Single-Shot Absolute Phase Test COMPLETE")
    print(f"Total time: {t_end - t_start:.1f} seconds")
    print(f"Results saved to: {result_folder}")
    print("=" * 70)

    # Print result summary
    if result is not None:
        print(f"\nResult keys: {list(result.keys()) if isinstance(result, dict) else type(result)}")


if __name__ == '__main__':
    main()
